Feat/okp4 profile
okp4/.github pull request #1
Opened 2022-06-02 08:33 UTC by ccamel

First draft of the OKP4 profile that will appear on our organization's profile, visible to anyone (once published).

2022-06-03 08:56 UTC, ghost requested changes

2022-06-03 08:56 UTC, ghost commented on profile/README.md
> +`OKP4` is built on the [Cosmos SDK](https://v1.cosmos.network/sdk) 💫 & [Tendermint](https://tendermint.com/) consensus, and is designed to become a hub of data providers, developer communities, data
```suggestion
`OKP4` is built on the [Cosmos SDK](https://v1.cosmos.network/sdk) 💫 & [Tendermint](https://tendermint.com/) consensus, and is designed to become a hub of incentivized data providers, developers, data scientists & users collaborating to generate value from data and algorithms.
```

2022-06-03 09:34 UTC, ghost requested changes

2022-06-03 09:34 UTC, ghost commented on profile/README.md
> +After 3 years of development, OKP4's team is now composed of 20+ full-time people on track to enable scalable real-world decentralized coordination. Through powerful incentive mechanisms and innovati
```suggestion
After 3+ years of strategy, research and development, OKP4 is almost ready to become the foundation for a scalable Open Dataverse, unlocking a new wave of use cases through real-world decentralized coordination. Our team & community is building a set of tools at the infrastructure, protocol, data and application layers with UX, interoperability, privacy and security in mind, ready to ignite innovation through data sharing.
```

2022-06-03 11:01 UTC, amimart submitted a review, later dismissed

2022-06-03 11:29 UTC, fredericvilcot approved these changes, later dismissed
Great! 🚀

2022-06-03 11:33 UTC, fredericvilcot approved these changes

2022-06-03 11:45 UTC, tpelliet approved these changes

2022-06-03 14:18 UTC, amimart approved these changes

2022-06-04 07:46 UTC, MdechampG approved these changes

2022-06-04 08:39 UTC, merged